### ISSUE TITLE
Problème de filtre sur le nom

### ISSUE THREAD

**Issue by Mattheking6** [Tylosten/hybridImg#3]
Dans la pages "Les images".
Lorsque l'on utilise le filtre sur le Nom, tout va bien jusqu'à ce que le filtre ne réponde plus à aucune image.
A partir de ce moment, même si on supprime le filtre (un petit bouton de suppression serait bienvenu ;-) ) , on ne récupère pas les images. A moins de faire fonctionner les boutons de pagination, mais les comportements sont très étranges.

**Comment by Mattheking6** [comment]
On trouve le même problème sur le filtre "Auteurice" lorsque l'on passe par un état avec un filtre qui occasionne 0 résultats.
Sur tous les filtres probablement.

**Comment by Tylosten** [comment]
Corrigé au commit e2d8ab0718b7d919ad50353274eca502931db52d
